<?php

namespace Dunique\AntwanVanBoheemen\Core\Traits;

use Dunique\AntwanVanBoheemen\Core\Middleware\Middleware;


/**
 Trait HasMiddleware
 
 Provides a mechanism for handling middleware in a class. 
 Middleware classes are processed in a pipeline and can modify 
 or act on the incoming request before it is handled by the final callable.
 
 Example Usage:
 
 class Post extends AbstractRoute
 {
     use HasMiddleware;
     
     protected $middleware = [
         EvaluateRequestMiddleware::class,
     ];
     
     public function process() {
         // Process middleware and handle request
         return $this->handle(ee('dunique:Request'), function ($request) 
         {
             $controller = new \Dunique\AntwanVanBoheemen\Core\Controllers\PostController();
             
             if ($request->isPost()) {
                 return $controller->store($request);
             }
 
             return ee()->functions->redirect(ee()->functions->form_backtrack('-2'));
         });
     }
 }
 *
 * @package Dunique\AntwanVanBoheemen\Core\Traits
 */
trait HasMiddleware
{
  /**
   * Processes the middleware pipeline and delegates the request to the final callable.
   *
   * @param mixed $request The incoming request object to be processed.
   * @param callable $final The final callable that handles the request after middleware processing.
   * 
   * @throws \RuntimeException If the middleware array is not defined or invalid.
   * 
   * @return mixed The response generated by the final callable or middleware.
   */
  protected function handle($request, callable $final)
  {
    // Ensure the middleware property is defined and is an array
    if (!isset($this->middleware) || !is_array($this->middleware)) {
      throw new \RuntimeException("The class using HasMiddleware must define a middleware array.");
    }

    // Get the Middleware service
    $pipeline = new Middleware;

    // Add each middleware class to the service
    foreach ($this->middleware as $class) {
      $pipeline->add(new $class());
    }

    // Delegate handling to the service
    return $pipeline->handle($request, $final);
  }
}
