name: ddev-voedselbankexamenproject
services:
  db:
    build:
      context: /home/renzo/Assorti/Study/Examen/VoedselbankExamenProject/.ddev/.dbimageBuild
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ddev/ddev-dbserver-mysql-8.0:v1.24.10
        gid: "1000"
        uid: "1000"
        username: renzo
    cap_add:
      - SYS_NICE
    command: []
    container_name: ddev-VoedselbankExamenProject-db
    environment:
      BITNAMI_VOLUME_DIR: /bitnami/mysql
      COLUMNS: "80"
      DDEV_DATABASE: mysql:8.0
      DDEV_DATABASE_FAMILY: mysql
      DDEV_GID: "1000"
      DDEV_GOARCH: amd64
      DDEV_GOOS: linux
      DDEV_HOSTNAME: voedselbankexamenproject.ddev.site
      DDEV_PHP_VERSION: "8.3"
      DDEV_PRIMARY_URL: http://voedselbankexamenproject.ddev.site
      DDEV_PRIMARY_URL_PORT: "80"
      DDEV_PRIMARY_URL_WITHOUT_PORT: http://voedselbankexamenproject.ddev.site
      DDEV_PROJECT: VoedselbankExamenProject
      DDEV_PROJECT_TYPE: php
      DDEV_ROUTER_HTTP_PORT: "80"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SCHEME: http
      DDEV_SITENAME: VoedselbankExamenProject
      DDEV_TLD: ddev.site
      DDEV_UID: "1000"
      DDEV_USER: renzo
      DDEV_VERSION: v1.24.10
      DOCKER_IP: 127.0.0.1
      EE_ADMIN_EMAIL: mhjnieuwenburg@gmail.com
      EE_ADMIN_PASSWORD: ""
      EE_ADMIN_USERNAME: Admin
      EE_VERSION: 7.5.6
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      IS_DDEV_PROJECT: "true"
      LINES: "24"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/VoedselbankExamenProject-db/mysql_history
      NODE_VERSION: "23"
      PGDATABASE: db
      PGHOST: 127.0.0.1
      PGPASSWORD: db
      PGUSER: db
      POSTGRES_DB: db
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      TZ: Europe/Amsterdam
      USER: renzo
    extra_hosts:
      - host.docker.internal=host-gateway
    hostname: VoedselbankExamenProject-db
    healthcheck:
      timeout: 1m10s
      interval: 1s
      retries: 70
      start_period: 4m0s
      start_interval: 1s
    image: ddev/ddev-dbserver-mysql-8.0:v1.24.10-VoedselbankExamenProject-built
    labels:
      com.ddev.app-type: php
      com.ddev.approot: /home/renzo/Assorti/Study/Examen/VoedselbankExamenProject
      com.ddev.platform: ddev
      com.ddev.site-name: VoedselbankExamenProject
    networks:
      ddev_default: null
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 3306
        published: "32783"
        protocol: tcp
    restart: "no"
    stop_grace_period: 1m0s
    user: 1000:1000
    volumes:
      - type: volume
        source: database
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: /home/renzo/Assorti/Study/Examen/VoedselbankExamenProject/.ddev
        target: /mnt/ddev_config
        bind:
          create_host_path: true
      - type: bind
        source: /home/renzo/Assorti/Study/Examen/VoedselbankExamenProject/.ddev/db_snapshots
        target: /mnt/snapshots
        bind:
          create_host_path: true
      - type: volume
        source: ddev-global-cache
        target: /mnt/ddev-global-cache
        volume: {}
    working_dir: /home/renzo
  phpmyadmin:
    container_name: ddev-VoedselbankExamenProject-phpmyadmin
    depends_on:
      db:
        condition: service_started
        required: true
    environment:
      EE_ADMIN_EMAIL: mhjnieuwenburg@gmail.com
      EE_ADMIN_PASSWORD: ""
      EE_ADMIN_USERNAME: Admin
      EE_VERSION: 7.5.6
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      HTTP_EXPOSE: 8036:80
      HTTPS_EXPOSE: 8037:80
      NODE_VERSION: "23"
      PMA_HOST: db
      PMA_PASSWORD: root
      PMA_PORT: "3306"
      PMA_USER: root
      UPLOAD_LIMIT: 4000M
      VIRTUAL_HOST: voedselbankexamenproject.ddev.site
    expose:
      - "80"
    extra_hosts:
      - host.docker.internal=host-gateway
    healthcheck:
      timeout: 2s
      interval: 2m0s
      retries: 1
    image: phpmyadmin:5
    labels:
      com.ddev.approot: /home/renzo/Assorti/Study/Examen/VoedselbankExamenProject
      com.ddev.site-name: VoedselbankExamenProject
    networks:
      ddev_default: null
      default: null
    restart: "no"
    volumes:
      - type: bind
        source: /home/renzo/Assorti/Study/Examen/VoedselbankExamenProject/.ddev
        target: /mnt/ddev_config
        bind:
          create_host_path: true
      - type: volume
        source: ddev-global-cache
        target: /mnt/ddev-global-cache
        volume: {}
    working_dir: /root
  web:
    build:
      context: /home/renzo/Assorti/Study/Examen/VoedselbankExamenProject/.ddev/.webimageBuild
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ddev/ddev-webserver:v1.24.10
        DDEV_DATABASE: mysql:8.0
        DDEV_PHP_VERSION: "8.3"
        gid: "1000"
        uid: "1000"
        username: renzo
    cap_add:
      - SYS_PTRACE
    command:
      - /pre-start.sh
    container_name: ddev-VoedselbankExamenProject-web
    environment:
      COLUMNS: "80"
      COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
      COREPACK_HOME: /mnt/ddev-global-cache/corepack
      DDEV_APPROOT: /var/www/html
      DDEV_COMPOSER_ROOT: /var/www/html
      DDEV_DATABASE: mysql:8.0
      DDEV_DATABASE_FAMILY: mysql
      DDEV_DOCROOT: website/public_html
      DDEV_FILES_DIR: ""
      DDEV_FILES_DIRS: ""
      DDEV_GID: "1000"
      DDEV_GOARCH: amd64
      DDEV_GOOS: linux
      DDEV_HOSTNAME: voedselbankexamenproject.ddev.site
      DDEV_MUTAGEN_ENABLED: "false"
      DDEV_PHP_VERSION: "8.3"
      DDEV_PRIMARY_URL: http://voedselbankexamenproject.ddev.site
      DDEV_PRIMARY_URL_PORT: "80"
      DDEV_PRIMARY_URL_WITHOUT_PORT: http://voedselbankexamenproject.ddev.site
      DDEV_PROJECT: VoedselbankExamenProject
      DDEV_PROJECT_TYPE: php
      DDEV_ROUTER_HTTP_PORT: "80"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SCHEME: http
      DDEV_SITENAME: VoedselbankExamenProject
      DDEV_TLD: ddev.site
      DDEV_UID: "1000"
      DDEV_USER: renzo
      DDEV_VERSION: v1.24.10
      DDEV_WEB_ENTRYPOINT: /mnt/ddev_config/web-entrypoint.d
      DDEV_WEBSERVER_TYPE: apache-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DDEV_XHPROF_MODE: prepend
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: website/public_html
      DRUSH_OPTIONS_URI: http://voedselbankexamenproject.ddev.site
      EE_ADMIN_EMAIL: mhjnieuwenburg@gmail.com
      EE_ADMIN_PASSWORD: ""
      EE_ADMIN_USERNAME: Admin
      EE_VERSION: 7.5.6
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      HTTP_EXPOSE: 80:80,8025:8025
      HTTPS_EXPOSE: 443:80,8026:8025
      IS_DDEV_PROJECT: "true"
      LINES: "24"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/VoedselbankExamenProject-web/mysql_history
      NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
      NODE_VERSION: "23"
      PGDATABASE: db
      PGHOST: db
      PGPASSWORD: db
      PGUSER: db
      PHP_IDE_CONFIG: serverName=VoedselbankExamenProject.ddev.site
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      START_SCRIPT_TIMEOUT: "117"
      TZ: Europe/Amsterdam
      USER: renzo
      VIRTUAL_HOST: voedselbankexamenproject.ddev.site
      npm_config_cache: /mnt/ddev-global-cache/npm
    extra_hosts:
      - host.docker.internal=host-gateway
    hostname: VoedselbankExamenProject-web
    healthcheck:
      timeout: 1m10s
      interval: 1s
      retries: 70
      start_period: 4m0s
      start_interval: 1s
    image: ddev/ddev-webserver:v1.24.10-VoedselbankExamenProject-built
    labels:
      com.ddev.app-type: php
      com.ddev.approot: /home/renzo/Assorti/Study/Examen/VoedselbankExamenProject
      com.ddev.platform: ddev
      com.ddev.site-name: VoedselbankExamenProject
    networks:
      ddev_default: null
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 80
        published: "32779"
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 443
        published: "32780"
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 8025
        protocol: tcp
    restart: "no"
    user: 1000:1000
    volumes:
      - type: bind
        source: /home/renzo/Assorti/Study/Examen/VoedselbankExamenProject
        target: /var/www/html
        consistency: cached
      - type: bind
        source: /home/renzo/Assorti/Study/Examen/VoedselbankExamenProject/.ddev
        target: /mnt/ddev_config
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /home/renzo/Assorti/Study/Examen/VoedselbankExamenProject/.ddev/xhprof
        target: /usr/local/bin/xhprof
        bind:
          create_host_path: true
      - type: volume
        source: ddev-global-cache
        target: /mnt/ddev-global-cache
        volume: {}
      - type: volume
        source: ddev-ssh-agent_socket_dir
        target: /home/.ssh-agent
        volume: {}
    working_dir: /var/www/html/
  xhgui:
    profiles:
      - xhgui
    container_name: ddev-VoedselbankExamenProject-xhgui
    depends_on:
      db:
        condition: service_started
        required: true
    environment:
      DDEV_DATABASE_FAMILY: mysql
      EE_ADMIN_EMAIL: mhjnieuwenburg@gmail.com
      EE_ADMIN_PASSWORD: ""
      EE_ADMIN_USERNAME: Admin
      EE_VERSION: 7.5.6
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      HTTP_EXPOSE: 8143:80
      HTTPS_EXPOSE: 8142:80
      NODE_VERSION: "23"
      TZ: Europe/Amsterdam
      VIRTUAL_HOST: voedselbankexamenproject.ddev.site
      XHGUI_PDO_PASS: db
      XHGUI_PDO_USER: db
      XHGUI_SAVE_HANDLER: pdo
    extra_hosts:
      - host.docker.internal=host-gateway
    image: ddev/ddev-xhgui:v1.24.10
    labels:
      com.ddev.approot: /home/renzo/Assorti/Study/Examen/VoedselbankExamenProject
      com.ddev.site-name: VoedselbankExamenProject
    networks:
      ddev_default: null
      default: null
    restart: "no"
    x-ddev:
      describe-url-port: 'Launch: ddev xhgui'
networks:
  ddev_default:
    name: ddev_default
    external: true
  default:
    name: ddev-voedselbankexamenproject_default
    labels:
      com.ddev.platform: ddev
volumes:
  database:
    name: VoedselbankExamenProject-mariadb
    external: true
  ddev-global-cache:
    name: ddev-global-cache
    external: true
  ddev-ssh-agent_socket_dir:
    name: ddev-ssh-agent_socket_dir
    external: true
